# Generated by Django 5.2.3 on 2025-06-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter the name of team: ', max_length=8)),
                ('stadium', models.CharField(help_text='Enter the name of stadium: ', max_length=15)),
                ('city', models.CharField(help_text='Enter the name of city: ', max_length=14)),
                ('slug', models.SlugField(editable=False, max_length=150)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]