
# Generated by Django 5.2.3 on 2025-06-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('final_result', models.CharField(max_length=10)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('guest_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_matches', to='team.team')),
                ('host_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_matches', to='team.team')),
            ],
        ),
    ]
